### ISSUE TITLE
Axios and API

### ISSUE THREAD

**Issue by Erkanamen** [bluesky0911/TestCodeForTodoAPP#1]
Hi there,

Just a few notes about tuto assignment. 
1. When running the code it seems to miss the import to `axios` on top of `TodoList.js`
2. Aren't we suppose to create our own mock-up API ? Because, first the URL isn't correct and second, if everyone is using the same API then there's some issue of concurrency ... (Another guy and me in the tuto, kept remove each other Todos)
3. What about keeping the completed status on the mock-up API as well ?

**Comment by bluesky0911** [comment]
Hello, I hope this answer can help you.

1. If you see the code of index.htmIl in public folder, there is  a line of code as below.
<script src="https://unpkg.com/axios@0.14.0/dist/axios.min.js"></script>	
Thus, you don't need to import the axios on the top of TodoList.js
-> This is for convenience for students who are not familiar with using web library.
-> I am not aiming to teach of the axios.

2. I think it might be OK to share the URL because the assignment for exercise does not target for saving and retrieving items from DB. Maybe it can cause a little confusion because when they access to the URL, there is possibility of remaining items created by others.
 -> If you want to create your own DB, you can use local array variable instead of using the URL.
 -> It is totally fine :)

3. Could you elaborate your third question ? - I could not get the meaning of it.

**Comment by bluesky0911** [comment]
Hm, actually, it might be a problem to share the URL when I see the codes again.
Thank you for your pointing out :)
I got understanding on your last question. 
I will fix and update the part of using the Axio library.  TodoList.js with using local array variable :) 

Thanks again!

**Comment by Erkanamen** [comment]
For 3, I wanted to say that we could additionally to the ID and text, store the current status of the ToDo element (completed/not completed) into the list stored in the API. But that was just to persist the current state that we inevitably have to take care of anyway with React. But sure, persistence is not we're looking into here anyway.

But for axios, it was more because when I first ran the code on my browser I add a js error. But I think I can look into that as well. During the tuto, I just `npm install axios --save-dev` for the purpose of having it, because I just thought it was missing, but didn't look into the other js imports in `index.html`

Sorry, I wrote the issue while leaving the tuto so it was slightly rushed indeed and may have been a bit confusing.

**Comment by bluesky0911** [comment]
I see, thank you for your feedback. 
Actually, I uploaded a new version of TodoList.js file and Index.html.
 - I remove the part of axio library. Thus, this discussion can be stopped here.
 - Instead of using axio library, I add array into the file for temporary DB :)

Thanks. I send announcement email to all students right now.

**Comment by Erkanamen** [comment]
Thats' all for me as well.

Thanks for checking it up !
